title: Eduardo Conde-Sousa
description: 
show_downloads: false
google_analytics: 
theme: jekyll-theme-hacker
listen_for_clients_preferred_style: true # false (default) or true
footer: 'follow me on <a href="https://twitter.com/econdesousa">twitter</a>'

plugins:
  - jekyll-redirect-from
github:
  repository_url: https://github.com/econdesousa/

#sidebar:
#  title: "Different Versions of me"
#  image: "https://econdesousa.github.io/assets/008_passe.gif"
#  image_alt: "Different Versions of me"
#  text: for more info on this image please click <a href="https://github.com/econdesousa/ImageAnalysis/tree/master/gifWithOverlay">here</a>!
  
